In [73]:
import numpy as np
import pandas as pd

In [74]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder


In [75]:
df = pd.read_csv('/content/covid_toy.csv')

In [76]:
df

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No
...,...,...,...,...,...,...
95,12,Female,104.0,Mild,Bangalore,No
96,51,Female,101.0,Strong,Kolkata,Yes
97,20,Female,101.0,Mild,Bangalore,No
98,5,Female,98.0,Strong,Mumbai,No


In [77]:
df['city'].value_counts()

,count
city,
Kolkata,32
Bangalore,30
Delhi,22
Mumbai,16


In [78]:
df['cough'].value_counts()

,count
cough,
Mild,62
Strong,38


In [79]:
df.isnull().sum()

,0
age,0
gender,0
fever,10
cough,0
city,0
has_covid,0


In [80]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['has_covid']),
                                                   df['has_covid'],
                                                   test_size = 0.2)

In [81]:
  X_train

,age,gender,fever,cough,city
78,11,Male,100.0,Mild,Bangalore
27,33,Female,102.0,Strong,Delhi
98,5,Female,98.0,Strong,Mumbai
3,31,Female,98.0,Mild,Kolkata
1,27,Male,100.0,Mild,Delhi
...,...,...,...,...,...
82,24,Male,98.0,Mild,Kolkata
60,24,Female,102.0,Strong,Bangalore
74,34,Female,104.0,Strong,Delhi
12,25,Female,99.0,Strong,Kolkata


In [82]:
X_test

,age,gender,fever,cough,city
31,83,Male,103.0,Mild,Kolkata
17,40,Female,98.0,Strong,Delhi
22,71,Female,98.0,Strong,Kolkata
79,48,Female,103.0,Mild,Kolkata
62,56,Female,104.0,Strong,Bangalore
46,19,Female,101.0,Mild,Mumbai
97,20,Female,101.0,Mild,Bangalore
57,49,Female,99.0,Strong,Bangalore
10,75,Female,NaN,Mild,Delhi
72,83,Female,101.0,Mild,Kolkata


# 1. Without using ColumnTransformer

In [83]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever

array([[100.        ],
       [102.        ],
       [ 98.        ],
       [ 98.        ],
       [100.        ],
       [102.        ],
       [101.        ],
       [103.        ],
       [ 98.        ],
       [104.        ],
       [ 99.        ],
       [104.        ],
       [100.        ],
       [ 98.        ],
       [ 98.        ],
       [ 98.        ],
       [104.        ],
       [102.        ],
       [101.        ],
       [104.        ],
       [100.81944444],
       [101.        ],
       [ 99.        ],
       [103.        ],
       [101.        ],
       [100.81944444],
       [101.        ],
       [104.        ],
       [100.        ],
       [102.        ],
       [101.        ],
       [ 99.        ],
       [ 98.        ],
       [ 99.        ],
       [102.        ],
       [101.        ],
       [104.        ],
       [103.        ],
       [100.        ],
       [104.        ],
       [100.81944444],
       [100.81944444],
       [100.81944444],
       [102

In [84]:
X_train_fever.shape

(80, 1)

In [85]:
# OrdinalEncoding -> cough
oe = OrdinalEncoder(categories=[['Mild', 'Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough

array([[0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],

In [86]:
X_train_cough.shape

(80, 1)

In [94]:
# OneHotEncoding -> gender, city

ohe = OneHotEncoder(drop = 'first')
X_train_gender_city = ohe.fit_transform(X_train[['gender', 'city']])
X_test_gender_city = ohe.fit_transform(X_test[['gender', 'city']])


In [103]:
X_train_gender_city = X_train_gender_city.toarray()

In [102]:
X_test_gender_city = X_test_gender_city.toarray()

In [104]:
# Extracting age

X_train_age = X_train.drop(columns = ['gender', 'fever', 'cough', 'city'])
X_train_age = X_train_age.values

X_test_age = X_test.drop(columns = ['gender', 'fever', 'cough', 'city'])
X_test_age = X_test_age.values

In [105]:
X_train_age

array([[11],
       [33],
       [ 5],
       [31],
       [27],
       [82],
       [15],
       [69],
       [34],
       [18],
       [14],
       [44],
       [19],
       [26],
       [73],
       [83],
       [25],
       [ 5],
       [81],
       [42],
       [20],
       [51],
       [22],
       [46],
       [14],
       [79],
       [19],
       [51],
       [10],
       [69],
       [42],
       [66],
       [64],
       [72],
       [49],
       [68],
       [17],
       [60],
       [27],
       [16],
       [38],
       [42],
       [34],
       [20],
       [ 5],
       [74],
       [81],
       [23],
       [65],
       [51],
       [ 8],
       [64],
       [50],
       [16],
       [82],
       [49],
       [11],
       [23],
       [13],
       [27],
       [60],
       [38],
       [70],
       [34],
       [75],
       [65],
       [80],
       [59],
       [80],
       [12],
       [84],
       [47],
       [47],
       [12],
       [10],
       [24],
       [24],

In [106]:
X_train_age.shape

(80, 1)

In [108]:
# Combining all the coloumns

X_train_transformed = np.concatenate((X_train_age, X_train_fever, X_train_gender_city, X_train_cough), axis = 1)

X_test_transformed = np.concatenate((X_test_age, X_test_fever, X_test_gender_city, X_test_cough), axis = 1)

X_train_transformed

array([[ 11.        , 100.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 33.        , 102.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [  5.        ,  98.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   1.        ],
       [ 31.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 27.        , 100.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 82.        , 102.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 15.        , 101.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 69.        , 103.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 34.        ,  98.        ,   1.        ,   0.        ,
          1.    

In [109]:
X_train_transformed.shape

(80, 7)

In [110]:
X_test_transformed

array([[ 83.        , 103.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 40.        ,  98.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 71.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 48.        , 103.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 56.        , 104.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 19.        , 101.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 20.        , 101.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 49.        ,  99.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 75.        , 100.94444444,   0.        ,   1.        ,
          0.    

# 2. Using ColumnTransformer

In [111]:
from sklearn.compose import ColumnTransformer

In [117]:
transformer = ColumnTransformer(transformers = [
    ('tnf1', SimpleImputer(), ['fever']),
    ('tnf2', OrdinalEncoder(categories = [['Mild', 'Strong']]), ['cough']),
    ('tnf3', OneHotEncoder(drop='first'), ['gender', 'city'])
], remainder = 'passthrough')  # passthrough means it does nothing to remaining columns

In [118]:
transformer.fit_transform(X_train)

array([[100.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  11.        ],
       [102.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  33.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   5.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  31.        ],
       [100.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  27.        ],
       [102.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  82.        ],
       [101.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  15.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  69.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          1.    

In [120]:
transformer.transform(X_test)

array([[103.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  83.        ],
       [ 98.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  40.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  71.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  48.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  56.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  19.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  20.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  49.        ],
       [100.81944444,   0.        ,   0.        ,   1.        ,
          0.    